# Generated by Django 3.2 on 2021-04-17 13:06

from django.db import migrations, models
import slowch.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('raw_content', models.TextField(max_length=10000, verbose_name='raw content')),
                ('html_content', models.TextField(blank=True, max_length=20000, null=True, verbose_name='html content')),
            ],
            bases=(models.Model, slowch.models.BaseMixins),
        ),
    ]
