# Generated by Django 3.2 on 2021-04-22 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_account_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMixins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('basemixins_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.basemixins')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('raw_content', models.TextField(max_length=10000, verbose_name='raw content')),
                ('html_content', models.TextField(blank=True, max_length=20000, null=True, verbose_name='html content')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.account', verbose_name='author')),
            ],
            bases=('article.basemixins',),
        ),
    ]
