# Generated by Django 3.2 on 2021-04-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_account_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.IntegerField(choices=[(0, 'admin'), (1, 'normal'), (2, 'normal plus')], default=1),
        ),
    ]
